# Generated by Django 4.0.4 on 2022-12-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Show_description',
            new_name='short_description',
        ),
    ]
