# Generated by Django 4.0.4 on 2022-12-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app1', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Default name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_size',
            field=models.CharField(choices=[{'1-9', 'size_1_9'}, {'10-49', 'size_10_49'}, {'50-99', 'size_50_99'}, {'size_100', '100+'}], default='size_1_9', max_length=20),
        ),
    ]
