# Generated by Django 4.0.4 on 2022-12-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app1', '0004_job_company_address_job_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(choices=[{'size_1-9', '1-9'}, {'10-49', 'size_10-49'}, {'size_50-99', '50-99'}, {'100+', 'size_100'}], default='size_1-9', max_length=20),
        ),
    ]
